/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "NeonMail"

include("plugin")
include("project:module-hook")
include("project:module-smtp")
include("project:common")
include("project:common-impl")
include("project:module-bukkit")
include("project:module-screen-vanilla")
include("project:module-screen-germ")
include("project:module-service")
include("project:module-template")
include("project:module-scheduler")
