/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "NeonMail-Premium"

include("plugin")
include("project:common")
include("project:module-bukkit")