/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "NeonMail-Premium"

include("plugin")
include("project:module-hook")
include("project:module-api")
include("project:module-common")
include("project:module-menu")
include("project:platform-bukkit")